# Panel Current Prediction with Weather Data

In [ ]:
import numpy as np
import pandas as pd

This section handles the initial setup, including importing necessary libraries and mounting Google Drive to access data files.

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Data Loading and Initial Processing (2024 Data)
This section focuses on loading the 2024 sensor data from Google Drive, copying it to the Colab environment for faster access, and performing an initial inspection.

In [ ]:
file_path = '/content/drive/MyDrive/Colab Notebooks/ansasol_tracker_2024.csv'

In [ ]:
import os
for root, dirs, files in os.walk('/content/drive/'):
    for file in files:
        if 'ansasol_tracker_2024.csv' in file:
            print(os.path.join(root, file))

/content/drive/MyDrive/Colab Notebooks/ansasol_tracker_2024.csv

In [ ]:
# Replace 'source_path' with the actual path of your file in Google Drive
# Replace 'destination_path' with the desired path in the local Colab environment
!cp "/content/drive/MyDrive/Colab Notebooks/ansasol_tracker_2024.csv" "/content/ansasol_tracker_2024.csv"

The 2024 data is loaded in chunks to manage memory efficiently, and then concatenated into a single Pandas DataFrame.

In [ ]:
chunk_size = 1050000
datadf = pd.read_csv('/content/ansasol_tracker_2024.csv',chunksize=chunk_size)
df = pd.concat(datadf, ignore_index=True)

Initial inspection of the 2024 DataFrame to understand its structure, data types, and the number of records.

In [ ]:
df.dtypes

inserted_datetime            object
UniqueKey                    object
DATA                          int64
Longitude                   float64
Latitude                    float64
DAS                           int64
TAS                           int64
MbAddress_PUB                 int64
Alarms1                       int64
Alarms2                       int64
HardwareId                    int64
SoftwareId                    int64
BTActive_a1                   int64
SleepState                    int64
CommissionState               int64
DayTime                       int64
MainState                     int64
AccessGranted                 int64
CraneManualControl            int64
PcManualControl               int64
SafePositionState             int64
AlarmStopButton               int64
AlarmSystemMonitor            int64
AlarmCom                      int64
AlarmZigbee                   int64
AlarmLimitedBatt              int64
AlarmNotEnoughBatt            int64
AlarmLowBatt                  int64
AlarmCriticalBatt             int64
AlarmTimeNeverSet             int64
AlarmMotor1OverCurrentHw      int64
AlarmMotor1OverCurrentSw      int64
AlarmAxis1Blocked             int64
AlarmAxis1LowSpeed            int64
FlagLsSwTop1                  int64
FlagLsSwBot1                  int64
FlagNewSwAvailable            int64
FlagStartAllowed              int64
FlagManual                    int64
FlagHold1                     int64
FlagSystemOk                  int64
PanelVoltage_mV               int64
Position_a1_rad             float64
MotorCurrent_a1_mA            int64
MotorCurrentPeak_a1_mA        int64
TargetAngle_a1_rad          float64
PanelCurrent_mA               int64
StateOfCharge                 int64
RemainingCapatity_mAh         int64
FullCapatity_mAh              int64
Voltage_mV                    int64
AvgCurrent_mA                 int64
Current_mA                    int64
TempPcb_Kx10                  int64
TempBat_Kx10                  int64
StateOfHealth                 int64
dtype: object

In [ ]:
df.head()
len(df)

6763707

## Dask Integration
Using Dask to handle large datasets more efficiently, especially for operations that might exceed available RAM.

This cell installs the Dask library and imports its `dataframe` module, enabling efficient handling of large datasets.

In [ ]:
!pip install dask[dataframe]  # Install Dask if not already installed

import dask.dataframe as dd

Collecting dask[dataframe]
  Downloading dask-2024.4.2-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 7.0 MB/s eta 0:00:00
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (8.1.7)
Requirement already satisfied: cloudpickle>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (2024.3.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (24.0)
Collecting partd>=1.2.0 (from dask[dataframe])
  Downloading partd-1.4.1-py3-none-any.whl (18 kB)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (6.0.1)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (0.12.1)
Collecting importlib-metadata>=4.13.0 (from dask[dataframe])
  Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pandas>=1.3 in /usr/local/lib/python3.10/dist-packages (from dask[dataframe]) (2.0.3)
Collecting dask-expr<1.1,>=1.0 (from dask[dataframe])
  Downloading dask_expr-1.0.13-py3-none-any.whl (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.1/195.1 kB 17.1 MB/s eta 0:00:00
Collecting pyarrow>=7.0.0 (from dask-expr<1.1,>=1.0->dask[dataframe])
  Downloading pyarrow-16.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 21.6 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=4.13.0->dask[dataframe]) (3.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3->dask[dataframe]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3->dask[dataframe]) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3->dask[dataframe]) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3->dask[dataframe]) (1.25.2)
Collecting locket (from partd>=1.2.0->dask[dataframe])
  Downloading locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3->dask[dataframe]) (1.16.0)
Installing collected packages: pyarrow, locket, importlib-metadata, partd, dask, dask-expr
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.6.4
    Uninstalling importlib-metadata-4.6.4:
      Successfully uninstalled importlib-metadata-4.6.4
Successfully installed dask-2024.4.2 dask-expr-1.0.13 importlib-metadata-7.1.0 locket-1.0.0 partd-1.4.1 pyarrow-16.0.0

## Data Loading and Initial Processing (2023 Data - Bypassed for RAM Capacity)
This section outlines the process for loading the 2023 sensor data, with a note on bypassing full processing due to memory constraints.

# New Section

#BYPASSING 2023 DATA BECAUSE OF RAM CAPACITY

Specifying the file path for the 2023 sensor data in Google Drive.

In [ ]:
file_path_1 = '/content/drive/MyDrive/Colab Notebooks/ansasol_tracker_2023.csv'

Verifying the file path for the 2023 sensor data by walking through the Google Drive directory structure.

In [ ]:
import os

for root, dirs, files in os.walk('/content/drive/'):
    for file in files:
        if 'ansasol_tracker_2023.csv' in file:
            print(os.path.join(root, file))

/content/drive/MyDrive/Colab Notebooks/ansasol_tracker_2023.csv

Copying the 2023 sensor data file from Google Drive to the local Colab environment for faster access.

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/ansasol_tracker_2023.csv" "/content/ansasol_tracker_2023.csv"

Loading the 2023 sensor data into a Pandas DataFrame. Although Dask is imported, the data is loaded directly with Pandas here to fit the current processing flow, noting potential memory implications for larger files.

In [ ]:
import dask.dataframe as dd

# Read the file with Dask
dask_df = pd.read_csv('/content/ansasol_tracker_2023.csv')

# Compute operations like in pandas
#dask_df = dask_df.compute()

Checking the number of records in the 2023 dataset.

In [ ]:
len(dask_df.index)

36167641

Combining the 2023 and 2024 sensor data into a single DataFrame for unified analysis.

In [ ]:
df_combined = pd.concat([dask_df, df], ignore_index=True)
#df_combined=df_combined.compute()

This markdown cell clarifies that the previous bypass of 2023 data due to RAM constraints is now concluded, and the combined dataset is ready for further processing.

#BYPASS ENDED

Confirming the total number of records in the combined DataFrame.

In [ ]:
#df_combined= df

In [ ]:
len(df_combined.index)
#df_combined.head()

42931348

Counting unique `inserted_datetime` values in the combined DataFrame to check for distinct time entries.

In [ ]:
df_combined['inserted_datetime'].nunique()

42725478

Displaying the data types of columns in the combined DataFrame for consistency and to identify any needing conversion.

In [ ]:
df.dtypes

inserted_datetime            object
UniqueKey                    object
DATA                          int64
Longitude                   float64
Latitude                    float64
DAS                           int64
TAS                           int64
MbAddress_PUB                 int64
Alarms1                       int64
Alarms2                       int64
HardwareId                    int64
SoftwareId                    int64
BTActive_a1                   int64
SleepState                    int64
CommissionState               int64
DayTime                       int64
MainState                     int64
AccessGranted                 int64
CraneManualControl            int64
PcManualControl               int64
SafePositionState             int64
AlarmStopButton               int64
AlarmSystemMonitor            int64
AlarmCom                      int64
AlarmZigbee                   int64
AlarmLimitedBatt              int64
AlarmNotEnoughBatt            int64
AlarmLowBatt                  int64
AlarmCriticalBatt             int64
AlarmTimeNeverSet             int64
AlarmMotor1OverCurrentHw      int64
AlarmMotor1OverCurrentSw      int64
AlarmAxis1Blocked             int64
AlarmAxis1LowSpeed            int64
FlagLsSwTop1                  int64
FlagLsSwBot1                  int64
FlagNewSwAvailable            int64
FlagStartAllowed              int64
FlagManual                    int64
FlagHold1                     int64
FlagSystemOk                  int64
PanelVoltage_mV               int64
Position_a1_rad             float64
MotorCurrent_a1_mA            int64
MotorCurrentPeak_a1_mA        int64
TargetAngle_a1_rad          float64
PanelCurrent_mA               int64
StateOfCharge                 int64
RemainingCapatity_mAh         int64
FullCapatity_mAh              int64
Voltage_mV                    int64
AvgCurrent_mA                 int64
Current_mA                    int64
TempPcb_Kx10                  int64
TempBat_Kx10                  int64
StateOfHealth                 int64
dtype: object

After inspecting the data types, this step is crucial for data consistency and preparation for analysis.

In [ ]:
df_combined = df_combined.drop_duplicates(subset=['inserted_datetime'])

This step removes duplicate entries based on the `inserted_datetime` column to ensure each timestamp represents a unique record.

In [ ]:
columns_to_drop = [
    'AccessGranted', 'CraneManualControl', 'PcManualControl', 'SafePositionState',
    'AlarmStopButton', 'AlarmSystemMonitor', 'AlarmCom', 'AlarmZigbee',
    'AlarmLimitedBatt', 'AlarmNotEnoughBatt', 'AlarmLowBatt', 'AlarmCriticalBatt',
    'AlarmTimeNeverSet', 'AlarmMotor1OverCurrentHw', 'AlarmMotor1OverCurrentSw',
    'AlarmAxis1Blocked', 'AlarmAxis1LowSpeed', 'FlagLsSwTop1', 'FlagLsSwBot1',
    'FlagNewSwAvailable', 'FlagStartAllowed', 'FlagManual', 'FlagHold1', 'FlagSystemOk'
]

# Drop
df_combined = df_combined.drop(columns=columns_to_drop)

These columns are dropped as they are not relevant for the prediction task or contain redundant information.

In [ ]:
df_combined['Splitdt']= pd.to_datetime(df_combined['inserted_datetime'])
df_combined.loc[:, 'Date'] = df_combined['Splitdt'].dt.date
df_combined.loc[:, 'Time'] = df_combined['Splitdt'].dt.hour
df_combined.loc[:, 'Date'] = df_combined['Date'].apply(lambda x: x.toordinal())

Here, the `inserted_datetime` column is converted to datetime objects, and then `Date` and `Time` features are extracted and converted for unique key creation.

In [ ]:
df_combined['Date']=df_combined['Date'].astype(str)
df_combined['Time']=df_combined['Time'].astype(str)
df_combined['UniqueKey_weather'] = df_combined[['Date','Time']].apply('-'.join,axis=1)

The `Date` and `Time` columns are formatted as strings and combined to create a unique key for merging with weather data.

In [ ]:
len(df_combined['inserted_datetime'])

42725478

Confirming the length of the processed `df_combined` DataFrame.

In [ ]:
df_combined.head()

,inserted_datetime,UniqueKey,DATA,Longitude,Latitude,DAS,TAS,MbAddress_PUB,Alarms1,Alarms2,...,Voltage_mV,AvgCurrent_mA,Current_mA,TempPcb_Kx10,TempBat_Kx10,StateOfHealth,Splitdt,Date,Time,UniqueKey_weather
0,2023-06-25T05:20:47.132Z,Archidona-2_NCU01_GW01A_17,20230625052705,-4.423389,37.090112,100,100,17,0,0,...,28776,0,0,2959,2934,100,2023-06-25 05:20:47.132000+00:00,738696,5,738696-5
1,2023-06-25T06:25:40.629Z,Archidona-2_NCU02_GW02A_11,20230625062707,-4.424557,37.082646,100,100,11,0,0,...,29000,4,0,2993,2948,100,2023-06-25 06:25:40.629000+00:00,738696,6,738696-6
2,2023-07-27T01:47:20.012Z,Archidona-2_NCU02_GW02A_38,20230727015237,-4.423072,37.083984,100,100,38,0,0,...,28216,0,0,2933,2935,100,2023-07-27 01:47:20.012000+00:00,738728,1,738728-1
3,2023-07-12T09:20:16.261Z,Archidona-2_NCU02_GW02A_27,20230712092430,-4.423610,37.086364,100,100,27,0,0,...,26680,0,0,3163,3088,100,2023-07-12 09:20:16.261000+00:00,738713,9,738713-9
4,2023-07-12T08:10:16.489Z,Archidona-2_NCU02_GW02B_71,20230712081228,-4.423990,37.085392,100,100,71,0,0,...,26784,0,0,3108,3025,100,2023-07-12 08:10:16.489000+00:00,738713,8,738713-8

Displaying the first few rows of the `df_combined` DataFrame to review the changes and newly created features.

In [ ]:
file_path_2 = '/content/drive/MyDrive/Colab Notebooks/ansasol_weather_update.csv'

## Weather Data Processing
This section loads and prepares the weather data for merging with the sensor data.

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/ansasol_weather_update.csv" "/content/ansasol_weather_update.csv"

Copying the weather data file from Google Drive to the local Colab environment for faster access.

In [ ]:
watherdf = pd.read_csv('/content/ansasol_weather_update.csv')

# Compute operations like in pandas
#watherdf = watherdf.compute()

Loading the weather data into a Pandas DataFrame.

In [ ]:
watherdf['inserted_datetime'].nunique()

72487

Counting the number of unique `inserted_datetime` values in the weather DataFrame.

In [ ]:
watherdf = watherdf.drop_duplicates(subset=['inserted_datetime'])

Removing duplicate entries based on `inserted_datetime` in the weather DataFrame.

In [ ]:
len(watherdf.index)

72487

Confirming the length of the weather DataFrame after dropping duplicates.

In [ ]:
watherdf.head()

,Unnamed: 0,inserted_datetime,weather,temperature,humidity,pressure,temp_unit,humidity_unit,pressure_unit
0,0,2024-02-07T13:35:08.117Z,clear sky,20.96,43.0,1024.0,°C,%,hPa
1,1,2024-02-07T14:50:08.117Z,clear sky,21.13,43.0,1024.0,°C,%,hPa
2,2,2024-02-07T15:05:08.103Z,clear sky,21.61,43.0,1024.0,°C,%,hPa
3,3,2024-02-07T15:07:47.587Z,clear sky,21.61,43.0,1024.0,°C,%,hPa
4,4,2024-02-07T15:20:08.090Z,clear sky,21.59,43.0,1024.0,°C,%,hPa

Displaying the first few rows of the weather DataFrame.

In [ ]:
watherdf['inserted_datetime'] = pd.to_datetime(watherdf['inserted_datetime'], format='ISO8601')
watherdf['inserted_datetime']= pd.to_datetime(watherdf['inserted_datetime'])

Converting the `inserted_datetime` column in the weather DataFrame to datetime objects.

Extracting `Date` and `Time` from the `inserted_datetime` column and converting `Date` to its ordinal representation for the weather data.

In [ ]:
watherdf['Splitdt']= pd.to_datetime(watherdf['inserted_datetime'])
watherdf.loc[:, 'Date'] = watherdf['Splitdt'].dt.date
watherdf.loc[:, 'Time'] = watherdf['Splitdt'].dt.hour
watherdf.loc[:, 'Date'] = watherdf['Date'].apply(lambda x: x.toordinal())

Converting `Date` and `Time` columns to string type and creating a `UniqueKey_weather` for merging.

In [ ]:
watherdf['Date']=watherdf['Date'].astype(str)
watherdf['Time']=watherdf['Time'].astype(str)
watherdf['UniqueKey_weather'] = watherdf[['Date','Time']].apply('-'.join,axis=1)

Displaying the head of the weather DataFrame with the new `UniqueKey_weather`.

In [ ]:
watherdf.head()

,Unnamed: 0,inserted_datetime,weather,temperature,humidity,pressure,temp_unit,humidity_unit,pressure_unit,Splitdt,Date,Time,UniqueKey_weather
0,0,2024-02-07 13:35:08.117000+00:00,clear sky,20.96,43.0,1024.0,°C,%,hPa,2024-02-07 13:35:08.117000+00:00,738923,13,738923-13
1,1,2024-02-07 14:50:08.117000+00:00,clear sky,21.13,43.0,1024.0,°C,%,hPa,2024-02-07 14:50:08.117000+00:00,738923,14,738923-14
2,2,2024-02-07 15:05:08.103000+00:00,clear sky,21.61,43.0,1024.0,°C,%,hPa,2024-02-07 15:05:08.103000+00:00,738923,15,738923-15
3,3,2024-02-07 15:07:47.587000+00:00,clear sky,21.61,43.0,1024.0,°C,%,hPa,2024-02-07 15:07:47.587000+00:00,738923,15,738923-15
4,4,2024-02-07 15:20:08.090000+00:00,clear sky,21.59,43.0,1024.0,°C,%,hPa,2024-02-07 15:20:08.090000+00:00,738923,15,738923-15

Identifying and dropping irrelevant columns from the weather DataFrame before merging.

In [ ]:
columns_to_drop = ['inserted_datetime','weather','temp_unit','humidity_unit','pressure_unit','Splitdt','Date','Time'

]

# Drop
watherdfdrop = watherdf.drop(columns=columns_to_drop)
watherdfdrop.head()
watherdfdrop.dtypes

Unnamed: 0             int64
temperature          float64
humidity             float64
pressure             float64
UniqueKey_weather     object
dtype: object

Checking for duplicates in `UniqueKey_weather` and displaying data types of the processed weather DataFrame.

In [ ]:
duplicates = watherdfdrop['UniqueKey_weather'].duplicated().sum()
watherdfdrop.dtypes

UniqueKey_weather     object
Unnamed: 0           float64
temperature          float64
humidity             float64
pressure             float64
dtype: object

Grouping the weather data by `UniqueKey_weather` and averaging other columns to handle multiple weather entries for the same hour, then saving to a CSV.

In [ ]:
watherdfdrop = watherdfdrop.groupby('UniqueKey_weather').mean().reset_index()
len(watherdfdrop)
watherdfdrop.to_csv('watherdfdrop.csv')

## Merging Sensor and Weather Data
This section merges the processed sensor data with the prepared weather data.

In [ ]:
merged_df = pd.merge(watherdfdrop, df_combined, on=['UniqueKey_weather'], how='inner')

Performing an inner merge operation to combine the sensor and weather DataFrames based on `UniqueKey_weather`.

In [ ]:
len(merged_df.index)

39938011

Confirming the total number of records in the merged DataFrame.

In [ ]:
merged_df.to_parquet('/content/drive/My Drive/merged_df_full.parquet')

## Saving Merged Data
Saving the large merged DataFrame to Google Drive in Parquet format for efficient storage and retrieval.

In [ ]:
file_path = '/content/drive/My Drive/large_dataframe.csv'
merged_df.to_csv(file_path, index=False, compression='gzip')

Saving the merged DataFrame to a gzipped CSV file for an alternative storage format.

In [ ]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 2.4 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

## Reloading Merged Data and Initial Analysis
This section reloads the merged data for further analysis, focusing on a specific tracker, and splits the data for testing.

In [ ]:
file_fnal = '/content/drive/My Drive/merged_df_full.parquet'

Copying the Parquet file back to the Colab environment to facilitate quicker processing.

In [ ]:
!cp "/content/drive/My Drive/merged_df_full.parquet" "/content/merged_df_full.parquet"

Loading the final merged Parquet file using Dask for efficient handling of large datasets and displaying its head.

In [ ]:
import dask.dataframe as dd

# Load the Parquet file using Dask
mergeddf_final = dd.read_parquet('merged_df_full.parquet')
mergeddf_final.head()

,UniqueKey_weather,Unnamed: 0,temperature,humidity,pressure,inserted_datetime,UniqueKey,DATA,Longitude,Latitude,...,FullCapatity_mAh,Voltage_mV,AvgCurrent_mA,Current_mA,TempPcb_Kx10,TempBat_Kx10,StateOfHealth,Splitdt,Date,Time
0,738521-0,39611.0,11.938,60.6,1027.0,2023-01-01T00:25:11.716Z,Archidona_NCU01_GW01B_67,20230101002446,-4.423661,37.094037,...,5722,26848,0,0,2818,2780,100,2023-01-01 00:25:11.716000+00:00,738521,0
1,738521-0,39611.0,11.938,60.6,1027.0,2023-01-01T00:35:11.764Z,Archidona_NCU01_GW01B_83,20230101002946,-4.422662,37.093559,...,5611,27848,1163,1163,2823,2796,100,2023-01-01 00:35:11.764000+00:00,738521,0
2,738521-0,39611.0,11.938,60.6,1027.0,2023-01-01T00:45:12.050Z,Archidona_NCU02_GW02B_29,20230101004446,-4.424101,37.094976,...,5606,28368,0,0,2803,2778,100,2023-01-01 00:45:12.050000+00:00,738521,0
3,738521-0,39611.0,11.938,60.6,1027.0,2023-01-01T00:20:11.988Z,Archidona_NCU02_GW02B_40,20230101001945,-4.423149,37.096722,...,5542,27600,0,0,2790,2779,100,2023-01-01 00:20:11.988000+00:00,738521,0
4,738521-0,39611.0,11.938,60.6,1027.0,2023-01-01T00:50:11.895Z,Archidona_NCU02_GW02A_20,20230101004946,-4.422766,37.095998,...,5751,27104,0,0,2827,2802,100,2023-01-01 00:50:11.895000+00:00,738521,0

Checking the total number of records in the Dask DataFrame `mergeddf_final`.

In [ ]:
len(mergeddf_final)

39938011

Grouping the `mergeddf_final` by `UniqueKey` to count occurrences and identify individual trackers with the most data.

In [ ]:
# Group by 'UniqueKey', count the occurrences, and compute the result
groupby_trackerid_df = mergeddf_final.groupby('UniqueKey').size().compute().reset_index(name='Count').sort_values(by='Count', ascending=False)

Printing the grouped DataFrame to show the count of records per unique tracker key.

In [ ]:
print(groupby_trackerid_df)

                      UniqueKey   Count
0     Archidona-2_NCU01_GW01A_1  137931
11    Archidona-2_NCU01_GW01A_2  137751
13   Archidona-2_NCU01_GW01A_21  137691
18    Archidona-2_NCU01_GW01A_4  137686
4    Archidona-2_NCU01_GW01A_13  137683
..                          ...     ...
281    Archidona_NCU02_GW02B_40   23243
292    Archidona_NCU02_GW02B_51   23240
294    Archidona_NCU02_GW02B_53   23233
284    Archidona_NCU02_GW02B_43   23190
273    Archidona_NCU02_GW02B_32   23041

[325 rows x 2 columns]

Filtering the `mergeddf_final` to select data for a specific tracker ('Archidona-2_NCU01_GW01A_2') and check its length.

In [ ]:
trackerdf= mergeddf_final[mergeddf_final['UniqueKey']=='Archidona-2_NCU01_GW01A_2']
len(trackerdf)

137751

Converting the Dask DataFrame `trackerdf` to a Pandas DataFrame for easier manipulation in subsequent steps.

In [ ]:
tracker_df_pandas = trackerdf.compute()

## Preparing Test Data
This section isolates the last 10,000 records of the selected tracker data for final testing.

#Seperate FinalTest Data

Extracting the last 10,000 rows from `tracker_df_pandas` to create a separate test dataset.

In [ ]:
tracker_GW02B_32_FTest= tracker_df_pandas.iloc[-10000:]

10000

Checking the type of `tracker_GW02B_32_FTest` and displaying its content (which is a Series in this case).

In [ ]:
print(type(tracker_GW02B_32_FTest))
tracker_GW02B_32_FTest.to_frame()

<class 'pandas.core.series.Series'>

        UniqueKey_weather
888476           738532-3
896419          738551-19
917209           738557-0
942958           738560-8
961993           738560-9
...                   ...
1102696          738568-1
1143449          738552-5
1164243          738557-4
1185094          738568-6
1205899          738534-0

[129 rows x 1 columns]

Removing duplicate `UniqueKey_weather` entries from the test set.

In [ ]:
tracker_GW02B_32_FTest=tracker_GW02B_32_FTest['UniqueKey_weather'].drop_duplicates()

KeyError: 'UniqueKey_weather'

Confirming the length of the processed test dataset.

In [ ]:
len(tracker_GW02B_32_FTest)

129

Removing the last 10,000 records (used for testing) from the `tracker_df_pandas` to form the training set.

In [ ]:
tracker_df_pandas.drop(tracker_df_pandas.tail(10000).index,
        inplace = True)

117628

Dropping duplicate `UniqueKey_weather` entries from the training set.

In [ ]:
tracker_df_pandas=tracker_df_pandas['UniqueKey_weather'].drop_duplicates()

Confirming the length of the training dataset after processing.

In [ ]:
len(tracker_df_pandas)

1326

## Saving Prepared Data
This section saves the separated test and training data for future use.

In [ ]:
#Saving Ftest data and Train and Test Data

"""for col in tracker_GW02B_32_FTest.select_dtypes(include=['datetime64[ns, UTC]']).columns:
    tracker_GW02B_32_FTest[col] = tracker_GW02B_32_FTest[col].dt.tz_localize(None)
"""
tracker_GW02B_32_FTest.to_parquet('tracker_GW02B_32_FTest.parquet')

AttributeError: 'Series' object has no attribute 'to_parquet'

Attempting to save the test DataFrame to a Parquet file. (Note: This might fail if `tracker_GW02B_32_FTest` is a Series and not a DataFrame).

In [ ]:
from google.colab import files
#tracker file
uploadedtracker=files.upload()

Saving tracker_df_pandas.parquet to tracker_df_pandas.parquet

## Library Imports and Data Loading
This section imports necessary libraries for modeling and reloads a tracker data file.

In [ ]:
tracker_df_pandas = pd.read_parquet('/content/tracker_df_pandas.parquet')

Loading a previously saved tracker DataFrame from a Parquet file.

In [ ]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set_style("darkgrid")
import warnings
import datetime as dt
warnings.filterwarnings("ignore")
import matplotlib.dates as mdates
import os
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso, Ridge

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

## Data Cleaning and Feature Engineering
This section focuses on preparing the data for model training by dropping irrelevant columns and creating numerical features.

In [ ]:
columns_to_drop = [
    'Splitdt_x', 'Date_x', 'Time_x', 'inserted_datetime_y', 'DATA', 'DAS', 'TAS',
    'MbAddress_PUB', 'Alarms1', 'Alarms2', 'HardwareId', 'SoftwareId',
    'BTActive_a1', 'Splitdt_y', 'Date_y', 'Time_y'
]

# Drop the specified columns
tracker_df_pandas.drop(columns=columns_to_drop, axis=1, inplace=True)

Dropping specified columns from the tracker DataFrame that are not needed for modeling.

In [ ]:
#created numericcal dataframe and runnin correlation
numericaltrackerdf= tracker_df_pandas.select_dtypes(include=['int64','float64'])
correlationmax= numericaltrackerdf.corr()
correlationmax=correlationmax.dropna(axis=1, how='all')
correlationmax=correlationmax.dropna(axis=0, how='all')
correlationmax.style.background_gradient(cmap='coolwarm')

Creating a numerical DataFrame and calculating the correlation matrix to understand relationships between numerical features.

In [ ]:
X = tracker_df_pandas[['temperature','humidity','pressure']]

## Model Training and Evaluation
This section prepares the data for machine learning models, trains various models, and evaluates their performance.

In [ ]:
y = tracker_df_pandas[['PanelCurrent_mA']]

Defining the target variable `y` (PanelCurrent_mA) for prediction.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Splitting the data into training and testing sets for model development and evaluation.

In [ ]:
print(len(X_train.index),len(X_test.index))

637909 159478

Printing the sizes of the training and testing sets.

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

### Linear Regression Model
Training a simple Linear Regression model.

In [ ]:
Y_pred = model.predict(X_test)

Making predictions on the test set using the trained Linear Regression model.

In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, Y_pred)))
print('R2 Score:', metrics.r2_score(y_test, Y_pred))

Mean Absolute Error: 2.457266194265159
Mean Squared Error: 12.518450044866475
Root Mean Squared Error: 3.5381421742019463
R2 Score: 0.22394422989315932

Evaluating the performance of the Linear Regression model using various metrics.

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
# Polynomial Regression
poly = PolynomialFeatures(degree=2)  # Try with degree=2, can increase based on dataset
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)
y_pred_poly = poly_model.predict(X_test_poly)

# Assess Polynomial Model
print("Polynomial Regression R^2:", r2_score(y_test, y_pred_poly))
print("Polynomial Regression MSE:", mean_squared_error(y_test, y_pred_poly))

Polynomial Regression R^2: 0.28304985109694825
Polynomial Regression MSE: 11.565025310573773

### Polynomial Regression Model
Implementing and evaluating a Polynomial Regression model for potentially better fit on non-linear relationships.

In [ ]:
from sklearn.svm import SVR
model = SVR(kernel='rbf')

### XGBoost Regressor Model
Setting up an XGBoost Regressor for advanced prediction, including hyperparameter tuning with Randomized Search.

In [ ]:
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV, train_test_split, StratifiedKFold
from sklearn.metrics import mean_squared_error
import time
from sklearn.model_selection import KFold
from sklearn.model_selection import RandomizedSearchCV

Importing necessary libraries for XGBoost and model selection.

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#Use only with GPU
#model = XGBRegressor(objective='reg:squarederror', tree_method='gpu_hist', learning_rate=0.02, n_estimators=1000)
model = XGBRegressor(objective='reg:squarederror', tree_method='hist', learning_rate=0.02, n_estimators=1000)

param_distributions = {
    'max_depth': [ 5, 7,9,11],
    'min_child_weight': [1, 5,10,12],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9],
    'n_estimators': [100, 500, 1000],
    'learning_rate': [0.01, 0.02,.1]
}
kf = KFold(n_splits=5, shuffle=True, random_state=1001)

random_search = RandomizedSearchCV(
    model,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=kf,
    verbose=3,
    random_state=1001,
    fit_params=fit_params
)

# early stopping
random_search.fit(X_train, y_train)

print("Best parameters:", random_search.best_params_)
print("Best score:", -random_search.best_score_)

best_model = random_search.best_estimator_
y_pred = best_model.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best parameters: {'subsample': 0.8, 'n_estimators': 1000, 'min_child_weight': 12, 'max_depth': 11, 'learning_rate': 0.1, 'colsample_bytree': 0.7}
Best score: 2.8753440471719536
MSE: 2.820797076666439

Configuring and running a Randomized Search for hyperparameter optimization of the XGBoost model, then evaluating its performance.

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

# Calculate RMSE
rmse = np.sqrt(mse)
print("RMSE:", rmse)

# Calculate MAE
mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

# Calculate R-squared
r2 = r2_score(y_test, y_pred)
print("R²:", r2)

MSE: 2.820797076666439
RMSE: 1.6795228717306707
MAE: 1.063927601256118
R²: 0.8251304402860005

Evaluating the best XGBoost model using MSE, RMSE, MAE, and R² metrics.

In [ ]:
import joblib

# Path to save the model in Google Drive
path = '/content/drive/My Drive/xgb_regressor.pkl'
# Save the model
joblib.dump(best_model, path)

['/content/drive/My Drive/xgb_regressor.pkl']

### Model Saving and Prediction
Saving the best trained XGBoost model and demonstrating its use with manual input.

In [ ]:
best_model = joblib.load(path)

Loading the saved XGBoost model for further use.

In [ ]:
manual_input = np.array([[23.57, 87, 1017]])

Creating a manual input array for testing the loaded model's prediction capability.

In [ ]:
predicted_value = best_model.predict(manual_input)
print("Predicted Value:", predicted_value[0])

Predicted Value: 100.48532

Predicting a value using the loaded model with the manual input.

## Conclusion
This notebook demonstrates a complete workflow from data loading and cleaning to model training, evaluation, and deployment for predicting panel current with weather data.